### ISSUE TITLE
Send SMS not working on Live site

### ISSUE THREAD

**Issue by parwinderD4D** [philnash/send-sms-react-twilio#1]
Hi, 

I have follow the instructions and its working fine on my local machine but when i try to run on my live server its not working, Could you please also let me know what changes i need to do so that it run on live server as well

**Comment by philnash** [comment]
Hi @parwinderD4D,

I didn't set this up well for deploying to a live server, but that's because it very much depends on how you want to deploy. In this example, I included the server side dependencies as `devDependencies` which wouldn't work for deploying live.

So, if you want to run this project on one server you would need to move the following dependencies from `devDependencies` to `dependencies`:

* `body-parser`
* `express`
* `express-pino-logger`
* `twilio`

You would also need a script that would run the server in production mode, something like:

```json
"scripts": {
  "server-production": "node server"
}
```

You'd need to build the React application as part of your deploy process. That is a case of running `npm run build`.

You would also need a way of serving the built React files from the express application, probably using [Express static](https://expressjs.com/en/starter/static-files.html).

These are some ideas, sorry I didn't think this through for the example. Let me know if it helps at all.

**Comment by parwinderD4D** [comment]
Hi @philnash
Thanks for reply,  I have follow this but not working, 

i have also added live site url in  package.json file under proxy 
 Example : ` "proxy":"http://abc.com"`

**Comment by philnash** [comment]
Hi @parwinderD4D,

So, you should not be running `npm run dev` in production, so using the `proxy` key will not help as that works with the webpack-dev-server that React is running in development.

If you have followed what I said, can you tell me what is not working? Which part is broken and how?

**Comment by philnash** [comment]
This is quite an old issue now, I'm going to close it. If you still need help, please feel free to re-open it.
